// countryData.ts
export interface Country {
    name: string
    iso2: string
    dialCode: string
    flag: string
  }
  
  export const countries: Country[] = [
    {
      name: 'Afghanistan',
      iso2: 'af',
      dialCode: '+93',
      flag: 'https://flagcdn.com/af.svg',
    },
    {
      name: 'Albania',
      iso2: 'al',
      dialCode: '+355',
      flag: 'https://flagcdn.com/al.svg',
    },
    {
      name: 'Algeria',
      iso2: 'dz',
      dialCode: '+213',
      flag: 'https://flagcdn.com/dz.svg',
    },
    {
      name: 'American Samoa',
      iso2: 'as',
      dialCode: '+1684',
      flag: 'https://flagcdn.com/as.svg',
    },
    {
      name: 'Andorra',
      iso2: 'ad',
      dialCode: '+376',
      flag: 'https://flagcdn.com/ad.svg',
    },
    {
      name: 'Angola',
      iso2: 'ao',
      dialCode: '+244',
      flag: 'https://flagcdn.com/ao.svg',
    },
    {
      name: 'Anguilla',
      iso2: 'ai',
      dialCode: '+1264',
      flag: 'https://flagcdn.com/ai.svg',
    },
    {
      name: 'Antarctica',
      iso2: 'aq',
      dialCode: '+672',
      flag: 'https://flagcdn.com/aq.svg',
    },
    {
      name: 'Antigua and Barbuda',
      iso2: 'ag',
      dialCode: '+1268',
      flag: 'https://flagcdn.com/ag.svg',
    },
    {
      name: 'Argentina',
      iso2: 'ar',
      dialCode: '+54',
      flag: 'https://flagcdn.com/ar.svg',
    },
    {
      name: 'Armenia',
      iso2: 'am',
      dialCode: '+374',
      flag: 'https://flagcdn.com/am.svg',
    },
    {
      name: 'Aruba',
      iso2: 'aw',
      dialCode: '+297',
      flag: 'https://flagcdn.com/aw.svg',
    },
    {
      name: 'Australia',
      iso2: 'au',
      dialCode: '+61',
      flag: 'https://flagcdn.com/au.svg',
    },
    {
      name: 'Austria',
      iso2: 'at',
      dialCode: '+43',
      flag: 'https://flagcdn.com/at.svg',
    },
    {
      name: 'Azerbaijan',
      iso2: 'az',
      dialCode: '+994',
      flag: 'https://flagcdn.com/az.svg',
    },
    {
      name: 'Bahamas',
      iso2: 'bs',
      dialCode: '+1242',
      flag: 'https://flagcdn.com/bs.svg',
    },
    {
      name: 'Bahrain',
      iso2: 'bh',
      dialCode: '+973',
      flag: 'https://flagcdn.com/bh.svg',
    },
    {
      name: 'Bangladesh',
      iso2: 'bd',
      dialCode: '+880',
      flag: 'https://flagcdn.com/bd.svg',
    },
    {
      name: 'Barbados',
      iso2: 'bb',
      dialCode: '+1246',
      flag: 'https://flagcdn.com/bb.svg',
    },
    {
      name: 'Belarus',
      iso2: 'by',
      dialCode: '+375',
      flag: 'https://flagcdn.com/by.svg',
    },
    {
      name: 'Belgium',
      iso2: 'be',
      dialCode: '+32',
      flag: 'https://flagcdn.com/be.svg',
    },
    {
      name: 'Belize',
      iso2: 'bz',
      dialCode: '+501',
      flag: 'https://flagcdn.com/bz.svg',
    },
    {
      name: 'Benin',
      iso2: 'bj',
      dialCode: '+229',
      flag: 'https://flagcdn.com/bj.svg',
    },
    {
      name: 'Bermuda',
      iso2: 'bm',
      dialCode: '+1441',
      flag: 'https://flagcdn.com/bm.svg',
    },
    {
      name: 'Bhutan',
      iso2: 'bt',
      dialCode: '+975',
      flag: 'https://flagcdn.com/bt.svg',
    },
    {
      name: 'Bolivia',
      iso2: 'bo',
      dialCode: '+591',
      flag: 'https://flagcdn.com/bo.svg',
    },
    {
      name: 'Bosnia and Herzegovina',
      iso2: 'ba',
      dialCode: '+387',
      flag: 'https://flagcdn.com/ba.svg',
    },
    {
      name: 'Botswana',
      iso2: 'bw',
      dialCode: '+267',
      flag: 'https://flagcdn.com/bw.svg',
    },
    {
      name: 'Brazil',
      iso2: 'br',
      dialCode: '+55',
      flag: 'https://flagcdn.com/br.svg',
    },
    {
      name: 'British Indian Ocean Territory',
      iso2: 'io',
      dialCode: '+246',
      flag: 'https://flagcdn.com/io.svg',
    },
    {
      name: 'British Virgin Islands',
      iso2: 'vg',
      dialCode: '+1284',
      flag: 'https://flagcdn.com/vg.svg',
    },
    {
      name: 'Brunei',
      iso2: 'bn',
      dialCode: '+673',
      flag: 'https://flagcdn.com/bn.svg',
    },
    {
      name: 'Bulgaria',
      iso2: 'bg',
      dialCode: '+359',
      flag: 'https://flagcdn.com/bg.svg',
    },
    {
      name: 'Burkina Faso',
      iso2: 'bf',
      dialCode: '+226',
      flag: 'https://flagcdn.com/bf.svg',
    },
    {
      name: 'Burundi',
      iso2: 'bi',
      dialCode: '+257',
      flag: 'https://flagcdn.com/bi.svg',
    },
    {
      name: 'Cambodia',
      iso2: 'kh',
      dialCode: '+855',
      flag: 'https://flagcdn.com/kh.svg',
    },
    {
      name: 'Cameroon',
      iso2: 'cm',
      dialCode: '+237',
      flag: 'https://flagcdn.com/cm.svg',
    },
    {
      name: 'Canada',
      iso2: 'ca',
      dialCode: '+1',
      flag: 'https://flagcdn.com/ca.svg',
    },
    {
      name: 'Cape Verde',
      iso2: 'cv',
      dialCode: '+238',
      flag: 'https://flagcdn.com/cv.svg',
    },
    {
      name: 'Caribbean Netherlands',
      iso2: 'bq',
      dialCode: '+599',
      flag: 'https://flagcdn.com/bq.svg',
    },
    {
      name: 'Cayman Islands',
      iso2: 'ky',
      dialCode: '+1345',
      flag: 'https://flagcdn.com/ky.svg',
    },
    {
      name: 'Central African Republic',
      iso2: 'cf',
      dialCode: '+236',
      flag: 'https://flagcdn.com/cf.svg',
    },
    {
      name: 'Chad',
      iso2: 'td',
      dialCode: '+235',
      flag: 'https://flagcdn.com/td.svg',
    },
    {
      name: 'Chile',
      iso2: 'cl',
      dialCode: '+56',
      flag: 'https://flagcdn.com/cl.svg',
    },
    {
      name: 'China',
      iso2: 'cn',
      dialCode: '+86',
      flag: 'https://flagcdn.com/cn.svg',
    },
    {
      name: 'Christmas Island',
      iso2: 'cx',
      dialCode: '+61',
      flag: 'https://flagcdn.com/cx.svg',
    },
    {
      name: 'Cocos Islands',
      iso2: 'cc',
      dialCode: '+61',
      flag: 'https://flagcdn.com/cc.svg',
    },
    {
      name: 'Colombia',
      iso2: 'co',
      dialCode: '+57',
      flag: 'https://flagcdn.com/co.svg',
    },
    {
      name: 'Comoros',
      iso2: 'km',
      dialCode: '+269',
      flag: 'https://flagcdn.com/km.svg',
    },
    {
      name: 'Congo (DRC)',
      iso2: 'cd',
      dialCode: '+243',
      flag: 'https://flagcdn.com/cd.svg',
    },
    {
      name: 'Congo (Republic)',
      iso2: 'cg',
      dialCode: '+242',
      flag: 'https://flagcdn.com/cg.svg',
    },
    {
      name: 'Cook Islands',
      iso2: 'ck',
      dialCode: '+682',
      flag: 'https://flagcdn.com/ck.svg',
    },
    {
      name: 'Costa Rica',
      iso2: 'cr',
      dialCode: '+506',
      flag: 'https://flagcdn.com/cr.svg',
    },
    {
      name: 'Côte d\'Ivoire',
      iso2: 'ci',
      dialCode: '+225',
      flag: 'https://flagcdn.com/ci.svg',
    },
    {
      name: 'Croatia',
      iso2: 'hr',
      dialCode: '+385',
      flag: 'https://flagcdn.com/hr.svg',
    },
    {
      name: 'Cuba',
      iso2: 'cu',
      dialCode: '+53',
      flag: 'https://flagcdn.com/cu.svg',
    },
    {
      name: 'Curaçao',
      iso2: 'cw',
      dialCode: '+599',
      flag: 'https://flagcdn.com/cw.svg',
    },
    {
      name: 'Cyprus',
      iso2: 'cy',
      dialCode: '+357',
      flag: 'https://flagcdn.com/cy.svg',
    },
    {
      name: 'Czech Republic',
      iso2: 'cz',
      dialCode: '+420',
      flag: 'https://flagcdn.com/cz.svg',
    },
    {
      name: 'Denmark',
      iso2: 'dk',
      dialCode: '+45',
      flag: 'https://flagcdn.com/dk.svg',
    },
    {
      name: 'Djibouti',
      iso2: 'dj',
      dialCode: '+253',
      flag: 'https://flagcdn.com/dj.svg',
    },
    {
      name: 'Dominica',
      iso2: 'dm',
      dialCode: '+1767',
      flag: 'https://flagcdn.com/dm.svg',
    },
    {
      name: 'Dominican Republic',
      iso2: 'do',
      dialCode: '+1809',
      flag: 'https://flagcdn.com/do.svg',
    },
    {
      name: 'Ecuador',
      iso2: 'ec',
      dialCode: '+593',
      flag: 'https://flagcdn.com/ec.svg',
    },
    {
      name: 'Egypt',
      iso2: 'eg',
      dialCode: '+20',
      flag: 'https://flagcdn.com/eg.svg',
    },
    {
      name: 'El Salvador',
      iso2: 'sv',
      dialCode: '+503',
      flag: 'https://flagcdn.com/sv.svg',
    },
    {
      name: 'Equatorial Guinea',
      iso2: 'gq',
      dialCode: '+240',
      flag: 'https://flagcdn.com/gq.svg',
    },
    {
      name: 'Eritrea',
      iso2: 'er',
      dialCode: '+291',
      flag: 'https://flagcdn.com/er.svg',
    },
    {
      name: 'Estonia',
      iso2: 'ee',
      dialCode: '+372',
      flag: 'https://flagcdn.com/ee.svg',
    },
    {
      name: 'Eswatini',
      iso2: 'sz',
      dialCode: '+268',
      flag: 'https://flagcdn.com/sz.svg',
    },
    {
      name: 'Ethiopia',
      iso2: 'et',
      dialCode: '+251',
      flag: 'https://flagcdn.com/et.svg',
    },
    {
      name: 'Falkland Islands',
      iso2: 'fk',
      dialCode: '+500',
      flag: 'https://flagcdn.com/fk.svg',
    },
    {
      name: 'Faroe Islands',
      iso2: 'fo',
      dialCode: '+298',
      flag: 'https://flagcdn.com/fo.svg',
    },
    {
      name: 'Fiji',
      iso2: 'fj',
      dialCode: '+679',
      flag: 'https://flagcdn.com/fj.svg',
    },
    {
      name: 'Finland',
      iso2: 'fi',
      dialCode: '+358',
      flag: 'https://flagcdn.com/fi.svg',
    },
    {
      name: 'France',
      iso2: 'fr',
      dialCode: '+33',
      flag: 'https://flagcdn.com/fr.svg',
    },
    {
      name: 'French Guiana',
      iso2: 'gf',
      dialCode: '+594',
      flag: 'https://flagcdn.com/gf.svg',
    },
    {
      name: 'French Polynesia',
      iso2: 'pf',
      dialCode: '+689',
      flag: 'https://flagcdn.com/pf.svg',
    },
    {
      name: 'Gabon',
      iso2: 'ga',
      dialCode: '+241',
      flag: 'https://flagcdn.com/ga.svg',
    },
    {
      name: 'Gambia',
      iso2: 'gm',
      dialCode: '+220',
      flag: 'https://flagcdn.com/gm.svg',
    },
    {
      name: 'Georgia',
      iso2: 'ge',
      dialCode: '+995',
      flag: 'https://flagcdn.com/ge.svg',
    },
    {
      name: 'Germany',
      iso2: 'de',
      dialCode: '+49',
      flag: 'https://flagcdn.com/de.svg',
    },
    {
      name: 'Ghana',
      iso2: 'gh',
      dialCode: '+233',
      flag: 'https://flagcdn.com/gh.svg',
    },
    {
      name: 'Gibraltar',
      iso2: 'gi',
      dialCode: '+350',
      flag: 'https://flagcdn.com/gi.svg',
    },
    {
      name: 'Greece',
      iso2: 'gr',
      dialCode: '+30',
      flag: 'https://flagcdn.com/gr.svg',
    },
    {
      name: 'Greenland',
      iso2: 'gl',
      dialCode: '+299',
      flag: 'https://flagcdn.com/gl.svg',
    },
    {
      name: 'Grenada',
      iso2: 'gd',
      dialCode: '+1473',
      flag: 'https://flagcdn.com/gd.svg',
    },
    {
      name: 'Guadeloupe',
      iso2: 'gp',
      dialCode: '+590',
      flag: 'https://flagcdn.com/gp.svg',
    },
    {
      name: 'Guam',
      iso2: 'gu',
      dialCode: '+1671',
      flag: 'https://flagcdn.com/gu.svg',
    },
    {
      name: 'Guatemala',
      iso2: 'gt',
      dialCode: '+502',
      flag: 'https://flagcdn.com/gt.svg',
    },
    {
      name: 'Guernsey',
      iso2: 'gg',
      dialCode: '+44',
      flag: 'https://flagcdn.com/gg.svg',
    },
    {
      name: 'Guinea',
      iso2: 'gn',
      dialCode: '+224',
      flag: 'https://flagcdn.com/gn.svg',
    },
    {
      name: 'Guinea-Bissau',
      iso2: 'gw',
      dialCode: '+245',
      flag: 'https://flagcdn.com/gw.svg',
    },
    {
      name: 'Guyana',
      iso2: 'gy',
      dialCode: '+592',
      flag: 'https://flagcdn.com/gy.svg',
    },
    {
      name: 'Haiti',
      iso2: 'ht',
      dialCode: '+509',
      flag: 'https://flagcdn.com/ht.svg',
    },
    {
      name: 'Honduras',
      iso2: 'hn',
      dialCode: '+504',
      flag: 'https://flagcdn.com/hn.svg',
    },
    {
      name: 'Hong Kong',
      iso2: 'hk',
      dialCode: '+852',
      flag: 'https://flagcdn.com/hk.svg',
    },
    {
      name: 'Hungary',
      iso2: 'hu',
      dialCode: '+36',
      flag: 'https://flagcdn.com/hu.svg',
    },
    {
      name: 'Iceland',
      iso2: 'is',
      dialCode: '+354',
      flag: 'https://flagcdn.com/is.svg',
    },
    {
      name: 'India',
      iso2: 'in',
      dialCode: '+91',
      flag: 'https://flagcdn.com/in.svg',
    },
    {
      name: 'Indonesia',
      iso2: 'id',
      dialCode: '+62',
      flag: 'https://flagcdn.com/id.svg',
    },
    {
      name: 'Iran',
      iso2: 'ir',
      dialCode: '+98',
      flag: 'https://flagcdn.com/ir.svg',
    },
    {
      name: 'Iraq',
      iso2: 'iq',
      dialCode: '+964',
      flag: 'https://flagcdn.com/iq.svg',
    },
    {
      name: 'Ireland',
      iso2: 'ie',
      dialCode: '+353',
      flag: 'https://flagcdn.com/ie.svg',
    },
    {
      name: 'Isle of Man',
      iso2: 'im',
      dialCode: '+44',
      flag: 'https://flagcdn.com/im.svg',
    },
    {
      name: 'Israel',
      iso2: 'il',
      dialCode: '+972',
      flag: 'https://flagcdn.com/il.svg',
    },
    {
      name: 'Italy',
      iso2: 'it',
      dialCode: '+39',
      flag: 'https://flagcdn.com/it.svg',
    },
    {
      name: 'Jamaica',
      iso2: 'jm',
      dialCode: '+1876',
      flag: 'https://flagcdn.com/jm.svg',
    },
    {
      name: 'Japan',
      iso2: 'jp',
      dialCode: '+81',
      flag: 'https://flagcdn.com/jp.svg',
    },
    {
      name: 'Jersey',
      iso2: 'je',
      dialCode: '+44',
      flag: 'https://flagcdn.com/je.svg',
    },
    {
      name: 'Jordan',
      iso2: 'jo',
      dialCode: '+962',
      flag: 'https://flagcdn.com/jo.svg',
    },
    {
      name: 'Kazakhstan',
      iso2: 'kz',
      dialCode: '+7',
      flag: 'https://flagcdn.com/kz.svg',
    },
    {
      name: 'Kenya',
      iso2: 'ke',
      dialCode: '+254',
      flag: 'https://flagcdn.com/ke.svg',
    },
    {
      name: 'Kiribati',
      iso2: 'ki',
      dialCode: '+686',
      flag: 'https://flagcdn.com/ki.svg',
    },
    {
      name: 'Kuwait',
      iso2: 'kw',
      dialCode: '+965',
      flag: 'https://flagcdn.com/kw.svg',
    },
    {
      name: 'Kyrgyzstan',
      iso2: 'kg',
      dialCode: '+996',
      flag: 'https://flagcdn.com/kg.svg',
    },
    {
      name: 'Laos',
      iso2: 'la',
      dialCode: '+856',
      flag: 'https://flagcdn.com/la.svg',
    },
    {
      name: 'Latvia',
      iso2: 'lv',
      dialCode: '+371',
      flag: 'https://flagcdn.com/lv.svg',
    },
    {
      name: 'Lebanon',
      iso2: 'lb',
      dialCode: '+961',
      flag: 'https://flagcdn.com/lb.svg',
    },
    {
      name: 'Lesotho',
      iso2: 'ls',
      dialCode: '+266',
      flag: 'https://flagcdn.com/ls.svg',
    },
    {
      name: 'Liberia',
      iso2: 'lr',
      dialCode: '+231',
      flag: 'https://flagcdn.com/lr.svg',
    },
    {
      name: 'Libya',
      iso2: 'ly',
      dialCode: '+218',
      flag: 'https://flagcdn.com/ly.svg',
    },
    {
      name: 'Liechtenstein',
      iso2: 'li',
      dialCode: '+423',
      flag: 'https://flagcdn.com/li.svg',
    },
    {
      name: 'Lithuania',
      iso2: 'lt',
      dialCode: '+370',
      flag: 'https://flagcdn.com/lt.svg',
    },
    {
      name: 'Luxembourg',
      iso2: 'lu',
      dialCode: '+352',
      flag: 'https://flagcdn.com/lu.svg',
    },
    {
      name: 'Macau',
      iso2: 'mo',
      dialCode: '+853',
      flag: 'https://flagcdn.com/mo.svg',
    },
    {
      name: 'Madagascar',
      iso2: 'mg',
      dialCode: '+261',
      flag: 'https://flagcdn.com/mg.svg',
    },
    {
      name: 'Malawi',
      iso2: 'mw',
      dialCode: '+265',
      flag: 'https://flagcdn.com/mw.svg',
    },
    {
      name: 'Malaysia',
      iso2: 'my',
      dialCode: '+60',
      flag: 'https://flagcdn.com/my.svg',
    },
    {
      name: 'Maldives',
      iso2: 'mv',
      dialCode: '+960',
      flag: 'https://flagcdn.com/mv.svg',
    },
    {
      name: 'Mali',
      iso2: 'ml',
      dialCode: '+223',
      flag: 'https://flagcdn.com/ml.svg',
    },
    {
      name: 'Malta',
      iso2: 'mt',
      dialCode: '+356',
      flag: 'https://flagcdn.com/mt.svg',
    },
    {
      name: 'Marshall Islands',
      iso2: 'mh',
      dialCode: '+692',
      flag: 'https://flagcdn.com/mh.svg',
    },
    {
      name: 'Martinique',
      iso2: 'mq',
      dialCode: '+596',
      flag: 'https://flagcdn.com/mq.svg',
    },
    {
      name: 'Mauritania',
      iso2: 'mr',
      dialCode: '+222',
      flag: 'https://flagcdn.com/mr.svg',
    },
    {
      name: 'Mauritius',
      iso2: 'mu',
      dialCode: '+230',
      flag: 'https://flagcdn.com/mu.svg',
    },
    {
      name: 'Mayotte',
      iso2: 'yt',
      dialCode: '+262',
      flag: 'https://flagcdn.com/yt.svg',
    },
    {
      name: 'Mexico',
      iso2: 'mx',
      dialCode: '+52',
      flag: 'https://flagcdn.com/mx.svg',
    },
    {
      name: 'Micronesia',
      iso2: 'fm',
      dialCode: '+691',
      flag: 'https://flagcdn.com/fm.svg',
    },
    {
      name: 'Moldova',
      iso2: 'md',
      dialCode: '+373',
      flag: 'https://flagcdn.com/md.svg',
    },
    {
      name: 'Monaco',
      iso2: 'mc',
      dialCode: '+377',
      flag: 'https://flagcdn.com/mc.svg',
    },
    {
      name: 'Mongolia',
      iso2: 'mn',
      dialCode: '+976',
      flag: 'https://flagcdn.com/mn.svg',
    },
    {
      name: 'Montenegro',
      iso2: 'me',
      dialCode: '+382',
      flag: 'https://flagcdn.com/me.svg',
    },
    {
      name: 'Montserrat',
      iso2: 'ms',
      dialCode: '+1664',
      flag: 'https://flagcdn.com/ms.svg',
    },
    {
      name: 'Morocco',
      iso2: 'ma',
      dialCode: '+212',
      flag: 'https://flagcdn.com/ma.svg',
    },
    {
      name: 'Mozambique',
      iso2: 'mz',
      dialCode: '+258',
      flag: 'https://flagcdn.com/mz.svg',
    },
    {
      name: 'Myanmar',
      iso2: 'mm',
      dialCode: '+95',
      flag: 'https://flagcdn.com/mm.svg',
    },
    {
      name: 'Namibia',
      iso2: 'na',
      dialCode: '+264',
      flag: 'https://flagcdn.com/na.svg',
    },
    {
      name: 'Nauru',
      iso2: 'nr',
      dialCode: '+674',
      flag: 'https://flagcdn.com/nr.svg',
    },
    {
      name: 'Nepal',
      iso2: 'np',
      dialCode: '+977',
      flag: 'https://flagcdn.com/np.svg',
    },
    {
      name: 'Netherlands',
      iso2: 'nl',
      dialCode: '+31',
      flag: 'https://flagcdn.com/nl.svg',
    },
    {
      name: 'New Caledonia',
      iso2: 'nc',
      dialCode: '+687',
      flag: 'https://flagcdn.com/nc.svg',
    },
    {
      name: 'New Zealand',
      iso2: 'nz',
      dialCode: '+64',
      flag: 'https://flagcdn.com/nz.svg',
    },
    {
      name: 'Nicaragua',
      iso2: 'ni',
      dialCode: '+505',
      flag: 'https://flagcdn.com/ni.svg',
    },
    {
      name: 'Niger',
      iso2: 'ne',
      dialCode: '+227',
      flag: 'https://flagcdn.com/ne.svg',
    },
    {
      name: 'Nigeria',
      iso2: 'ng',
      dialCode: '+234',
      flag: 'https://flagcdn.com/ng.svg',
    },
    {
      name: 'Niue',
      iso2: 'nu',
      dialCode: '+683',
      flag: 'https://flagcdn.com/nu.svg',
    },
    {
      name: 'Norfolk Island',
      iso2: 'nf',
      dialCode: '+672',
      flag: 'https://flagcdn.com/nf.svg',
    },
    {
      name: 'North Korea',
      iso2: 'kp',
      dialCode: '+850',
      flag: 'https://flagcdn.com/kp.svg',
    },
    {
      name: 'North Macedonia',
      iso2: 'mk',
      dialCode: '+389',
      flag: 'https://flagcdn.com/mk.svg',
    },
    {
      name: 'Northern Mariana Islands',
      iso2: 'mp',
      dialCode: '+1670',
      flag: 'https://flagcdn.com/mp.svg',
    },
    {
      name: 'Norway',
      iso2: 'no',
      dialCode: '+47',
      flag: 'https://flagcdn.com/no.svg',
    },
    {
      name: 'Oman',
      iso2: 'om',
      dialCode: '+968',
      flag: 'https://flagcdn.com/om.svg',
    },
    {
      name: 'Pakistan',
      iso2: 'pk',
      dialCode: '+92',
      flag: 'https://flagcdn.com/pk.svg',
    },
    {
      name: 'Palau',
      iso2: 'pw',
      dialCode: '+680',
      flag: 'https://flagcdn.com/pw.svg',
    },
    {
      name: 'Palestine',
      iso2: 'ps',
      dialCode: '+970',
      flag: 'https://flagcdn.com/ps.svg',
    },
    {
      name: 'Panama',
      iso2: 'pa',
      dialCode: '+507',
      flag: 'https://flagcdn.com/pa.svg',
    },
    {
      name: 'Papua New Guinea',
      iso2: 'pg',
      dialCode: '+675',
      flag: 'https://flagcdn.com/pg.svg',
    },
    {
      name: 'Paraguay',
      iso2: 'py',
      dialCode: '+595',
      flag: 'https://flagcdn.com/py.svg',
    },
    {
      name: 'Peru',
      iso2: 'pe',
      dialCode: '+51',
      flag: 'https://flagcdn.com/pe.svg',
    },
    {
      name: 'Philippines',
      iso2: 'ph',
      dialCode: '+63',
      flag: 'https://flagcdn.com/ph.svg',
    },
    {
      name: 'Poland',
      iso2: 'pl',
      dialCode: '+48',
      flag: 'https://flagcdn.com/pl.svg',
    },
    {
      name: 'Portugal',
      iso2: 'pt',
      dialCode: '+351',
      flag: 'https://flagcdn.com/pt.svg',
    },
    {
      name: 'Puerto Rico',
      iso2: 'pr',
      dialCode: '+1',
      flag: 'https://flagcdn.com/pr.svg',
    },
    {
      name: 'Qatar',
      iso2: 'qa',
      dialCode: '+974',
      flag: 'https://flagcdn.com/qa.svg',
    },
    {
      name: 'Réunion',
      iso2: 're',
      dialCode: '+262',
      flag: 'https://flagcdn.com/re.svg',
    },
    {
      name: 'Romania',
      iso2: 'ro',
      dialCode: '+40',
      flag: 'https://flagcdn.com/ro.svg',
    },
    {
      name: 'Russia',
      iso2: 'ru',
      dialCode: '+7',
      flag: 'https://flagcdn.com/ru.svg',
    },
    {
      name: 'Rwanda',
      iso2: 'rw',
      dialCode: '+250',
      flag: 'https://flagcdn.com/rw.svg',
    },
    {
      name: 'Saint Barthélemy',
      iso2: 'bl',
      dialCode: '+590',
      flag: 'https://flagcdn.com/bl.svg',
    },
    {
      name: 'Saint Helena',
      iso2: 'sh',
      dialCode: '+290',
      flag: 'https://flagcdn.com/sh.svg',
    },
    {
      name: 'Saint Kitts and Nevis',
      iso2: 'kn',
      dialCode: '+1869',
      flag: 'https://flagcdn.com/kn.svg',
    },
    {
      name: 'Saint Lucia',
      iso2: 'lc',
      dialCode: '+1758',
      flag: 'https://flagcdn.com/lc.svg',
    },
    {
      name: 'Saint Martin',
      iso2: 'mf',
      dialCode: '+590',
      flag: 'https://flagcdn.com/mf.svg',
    },
    {
      name: 'Saint Pierre and Miquelon',
      iso2: 'pm',
      dialCode: '+508',
      flag: 'https://flagcdn.com/pm.svg',
    },
    {
      name: 'Saint Vincent and the Grenadines',
      iso2: 'vc',
      dialCode: '+1784',
      flag: 'https://flagcdn.com/vc.svg',
    },
    {
      name: 'Samoa',
      iso2: 'ws',
      dialCode: '+685',
      flag: 'https://flagcdn.com/ws.svg',
    },
    {
      name: 'San Marino',
      iso2: 'sm',
      dialCode: '+378',
      flag: 'https://flagcdn.com/sm.svg',
    },
    {
      name: 'São Tomé and Príncipe',
      iso2: 'st',
      dialCode: '+239',
      flag: 'https://flagcdn.com/st.svg',
    },
    {
      name: 'Saudi Arabia',
      iso2: 'sa',
      dialCode: '+966',
      flag: 'https://flagcdn.com/sa.svg',
    },
    {
      name: 'Senegal',
      iso2: 'sn',
      dialCode: '+221',
      flag: 'https://flagcdn.com/sn.svg',
    },
    {
      name: 'Serbia',
      iso2: 'rs',
      dialCode: '+381',
      flag: 'https://flagcdn.com/rs.svg',
    },
    {
      name: 'Seychelles',
      iso2: 'sc',
      dialCode: '+248',
      flag: 'https://flagcdn.com/sc.svg',
    },
    {
      name: 'Sierra Leone',
      iso2: 'sl',
      dialCode: '+232',
      flag: 'https://flagcdn.com/sl.svg',
    },
    {
      name: 'Singapore',
      iso2: 'sg',
      dialCode: '+65',
      flag: 'https://flagcdn.com/sg.svg',
    },
    {
      name: 'Sint Maarten',
      iso2: 'sx',
      dialCode: '+1721',
      flag: 'https://flagcdn.com/sx.svg',
    },
    {
      name: 'Slovakia',
      iso2: 'sk',
      dialCode: '+421',
      flag: 'https://flagcdn.com/sk.svg',
    },
    {
      name: 'Slovenia',
      iso2: 'si',
      dialCode: '+386',
      flag: 'https://flagcdn.com/si.svg',
    },
    {
      name: 'Solomon Islands',
      iso2: 'sb',
      dialCode: '+677',
      flag: 'https://flagcdn.com/sb.svg',
    },
    {
      name: 'Somalia',
      iso2: 'so',
      dialCode: '+252',
      flag: 'https://flagcdn.com/so.svg',
    },
    {
      name: 'South Africa',
      iso2: 'za',
      dialCode: '+27',
      flag: 'https://flagcdn.com/za.svg',
    },
    {
      name: 'South Korea',
      iso2: 'kr',
      dialCode: '+82',
      flag: 'https://flagcdn.com/kr.svg',
    },
    {
      name: 'South Sudan',
      iso2: 'ss',
      dialCode: '+211',
      flag: 'https://flagcdn.com/ss.svg',
    },
    {
      name: 'Spain',
      iso2: 'es',
      dialCode: '+34',
      flag: 'https://flagcdn.com/es.svg',
    },
    {
      name: 'Sri Lanka',
      iso2: 'lk',
      dialCode: '+94',
      flag: 'https://flagcdn.com/lk.svg',
    },
    {
      name: 'Sudan',
      iso2: 'sd',
      dialCode: '+249',
      flag: 'https://flagcdn.com/sd.svg',
    },
    {
      name: 'Suriname',
      iso2: 'sr',
      dialCode: '+597',
      flag: 'https://flagcdn.com/sr.svg',
    },
    {
      name: 'Svalbard and Jan Mayen',
      iso2: 'sj',
      dialCode: '+47',
      flag: 'https://flagcdn.com/sj.svg',
    },
    {
      name: 'Sweden',
      iso2: 'se',
      dialCode: '+46',
      flag: 'https://flagcdn.com/se.svg',
    },
    {
      name: 'Switzerland',
      iso2: 'ch',
      dialCode: '+41',
      flag: 'https://flagcdn.com/ch.svg',
    },
    {
      name: 'Syria',
      iso2: 'sy',
      dialCode: '+963',
      flag: 'https://flagcdn.com/sy.svg',
    },
    {
      name: 'Taiwan',
      iso2: 'tw',
      dialCode: '+886',
      flag: 'https://flagcdn.com/tw.svg',
    },
    {
      name: 'Tajikistan',
      iso2: 'tj',
      dialCode: '+992',
      flag: 'https://flagcdn.com/tj.svg',
    },
    {
      name: 'Tanzania',
      iso2: 'tz',
      dialCode: '+255',
      flag: 'https://flagcdn.com/tz.svg',
    },
    {
      name: 'Thailand',
      iso2: 'th',
      dialCode: '+66',
      flag: 'https://flagcdn.com/th.svg',
    },
    {
      name: 'Timor-Leste',
      iso2: 'tl',
      dialCode: '+670',
      flag: 'https://flagcdn.com/tl.svg',
    },
    {
      name: 'Togo',
      iso2: 'tg',
      dialCode: '+228',
      flag: 'https://flagcdn.com/tg.svg',
    },
    {
      name: 'Tokelau',
      iso2: 'tk',
      dialCode: '+690',
      flag: 'https://flagcdn.com/tk.svg',
    },
    {
      name: 'Tonga',
      iso2: 'to',
      dialCode: '+676',
      flag: 'https://flagcdn.com/to.svg',
    },
    {
      name: 'Trinidad and Tobago',
      iso2: 'tt',
      dialCode: '+1868',
      flag: 'https://flagcdn.com/tt.svg',
    },
    {
      name: 'Tunisia',
      iso2: 'tn',
      dialCode: '+216',
      flag: 'https://flagcdn.com/tn.svg',
    },
    {
      name: 'Turkey',
      iso2: 'tr',
      dialCode: '+90',
      flag: 'https://flagcdn.com/tr.svg',
    },
    {
      name: 'Turkmenistan',
      iso2: 'tm',
      dialCode: '+993',
      flag: 'https://flagcdn.com/tm.svg',
    },
    {
      name: 'Turks and Caicos Islands',
      iso2: 'tc',
      dialCode: '+1649',
      flag: 'https://flagcdn.com/tc.svg',
    },
    {
      name: 'Tuvalu',
      iso2: 'tv',
      dialCode: '+688',
      flag: 'https://flagcdn.com/tv.svg',
    },
    {
      name: 'U.S. Virgin Islands',
      iso2: 'vi',
      dialCode: '+1340',
      flag: 'https://flagcdn.com/vi.svg',
    },
    {
      name: 'Uganda',
      iso2: 'ug',
      dialCode: '+256',
      flag: 'https://flagcdn.com/ug.svg',
    },
    {
      name: 'Ukraine',
      iso2: 'ua',
      dialCode: '+380',
      flag: 'https://flagcdn.com/ua.svg',
    },
    {
      name: 'United Arab Emirates',
      iso2: 'ae',
      dialCode: '+971',
      flag: 'https://flagcdn.com/ae.svg',
    },
    {
      name: 'United Kingdom',
      iso2: 'gb',
      dialCode: '+44',
      flag: 'https://flagcdn.com/gb.svg',
    },
    {
      name: 'United States',
      iso2: 'us',
      dialCode: '+1',
      flag: 'https://flagcdn.com/us.svg',
    },
    {
      name: 'Uruguay',
      iso2: 'uy',
      dialCode: '+598',
      flag: 'https://flagcdn.com/uy.svg',
    },
    {
      name: 'Uzbekistan',
      iso2: 'uz',
      dialCode: '+998',
      flag: 'https://flagcdn.com/uz.svg',
    },
    {
      name: 'Vanuatu',
      iso2: 'vu',
      dialCode: '+678',
      flag: 'https://flagcdn.com/vu.svg',
    },
    {
      name: 'Vatican City',
      iso2: 'va',
      dialCode: '+39',
      flag: 'https://flagcdn.com/va.svg',
    },
    {
      name: 'Venezuela',
      iso2: 've',
      dialCode: '+58',
      flag: 'https://flagcdn.com/ve.svg',
    },
    {
      name: 'Vietnam',
      iso2: 'vn',
      dialCode: '+84',
      flag: 'https://flagcdn.com/vn.svg',
    },
    {
      name: 'Wallis and Futuna',
      iso2: 'wf',
      dialCode: '+681',
      flag: 'https://flagcdn.com/wf.svg',
    },
    {
      name: 'Western Sahara',
      iso2: 'eh',
      dialCode: '+212',
      flag: 'https://flagcdn.com/eh.svg',
    },
    {
      name: 'Yemen',
      iso2: 'ye',
      dialCode: '+967',
      flag: 'https://flagcdn.com/ye.svg',
    },
    {
      name: 'Zambia',
      iso2: 'zm',
      dialCode: '+260',
      flag: 'https://flagcdn.com/zm.svg',
    },
    {
      name: 'Zimbabwe',
      iso2: 'zw',
      dialCode: '+263',
      flag: 'https://flagcdn.com/zw.svg',
    },
  ]
  